version: "2"

checks:
  method-lines:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

exclude_patterns:
  - "**/node_modules/"
  - "**/media/"
  - "**/test/"
  - ".eslint*"